services:
  id-postgres:
    container_name: id-postgres
    image: postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
  id-redis:
    container_name: id-redis
    image: redis
    env_file:
      - .env
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_PORT}:6379"

volumes:
  postgres_data:
  redis_data:
