services:
  id-postgres:
    container_name: id-postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=id
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 2s
      timeout: 2s
      retries: 10
  id-redis:
    container_name: id-redis
    image: redis
    environment:
      - REDIS_USER=default
      - REDIS_PASSWORD=redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli -a ${REDIS_PASSWORD} ping"]
      interval: 2s
      timeout: 2s
      retries: 10

volumes:
  postgres_data:
  redis_data:
